### ISSUE TITLE
Deprecate vending=parcel_pickup

### ISSUE THREAD

**Issue by overflorian** [plepe/openstreetbrowser-categories-main#45] opened 2022-01-18 15:11 UTC
Hi,
A new tag just [has been approved](https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker): [amenity=parcel_locker](https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker) and describes a parcel locker.
It replaces previously used (and now deprecated) amenity=vending_machine + vending=parcel_pickup

I propose to:
* Stop proposing the preset amenity=vending_machine + vending=parcel_pickup
* If applicable, stop proposing the preset amenity=vending_machine + vending=parcel_pickup;parcel_mail_in
* Create a new dedicated preset for amenity=parcel_locker

Thanks

PS: deprecation follow-up (including similar requests to other tools) is available on this wiki page: https://wiki.openstreetmap.org/wiki/Tag:vending%3Dparcel_pickup#Deprecation_follow-up

**Comment by plepe** [comment] 2022-01-18 19:30
Duplicate of #44.

As long as there are still relevant amounts of items of the old tagging around, I'd rather not remove the old queries. Currently: ~19000 (vs. <250 parcel_locker).

I can add a warning to old items though.

**Comment by plepe** [comment] 2022-01-20 19:31
Ok, I implemented a warning in the popup of those items. Also, the pin will have a red color, to indicate an error. I think, this is sufficiently solved. If you have ideas for improvements, please say so :-)
![Screenshot 2022-01-20 at 20-28-35 OpenStreetBrowser](https://user-images.githubusercontent.com/249012/150408979-f829fcd8-e0dd-4c6a-8a36-6ef2f32ded43.png)

**Closed by plepe** 2022-01-20 19:31 UTC

**Comment by plepe** [comment] 2022-01-23 12:54
I announced this here: https://www.openstreetmap.org/user/skunk/diary/398522

**Comment by overflorian** [comment] 2022-02-02 16:31
Very nice, thanks! I forwarded this info in the french community
